apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fraud-detection-binding
subjects:
  - kind: ServiceAccount
    name: fraud-detection-sa
roleRef:
  kind: Role
  name: fraud-detection-role
  apiGroup: rbac.authorization.k8s.io
