apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  labels:
    app: fraud-detection
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: fraud-detection
